[build]
  command = "npm install"
  functions = ".netlify/functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"
  
[build]
  functions = ".netlify/functions"